/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cowin;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class CowinBookApplication {
    public static void main(String args[]) {
    	SpringApplication.run(CowinBookApplication.class, args);
	}
}
